modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/BasiqueEvangelist/FlashFreeze/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "flashfreeze"
version = "${version}"
displayName = "FlashFreeze"
authors = "BasiqueEvangelist"
description = '''
Keep unknown blocks and items
'''
logoFile = "icon.png"

[[dependencies.flashfreeze]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.flashfreeze]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"